name: "Deploy BCSS Notify Lambdas"

on:
  workflow_run:
    workflows: ["Test stage"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        options:
          - dev
jobs:
  deploy-bcss-notify-lambdas:
    name: "Deploy BCSS Notify lambdas"
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} || ${{ github.event_name == 'workflow_dispatch' }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::730319765130:role/bcss-github-actions-lambda-access
          aws-region: eu-west-2
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - name: Install zip tool
        uses: montudor/action-zip@v1
      - name: Create zip file for Batch Notification Processor function
        run: cd batch_notification_processor && cp ../shared/*.py . && zip -r code.zip ./*.py
      - name: Update Batch Notification Processor lambda function code
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:eu-west-2:730319765130:function:bcss-comms-batch-notification-processor-dev \
            --zip-file fileb://batch_notification_processor/code.zip \
            --region eu-west-2
      - name: Create zip file for Message Status Handler function
        run: cd message_status_handler && cp ../shared/*.py . && zip -r code.zip ./*.py
      - name: Update Message Status Handler lambda function code
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:eu-west-2:730319765130:function:bcss-comms-message-status-handler-dev \
            --zip-file fileb://message_status_handler/code.zip \
            --region eu-west-2
      - name: Create zip file for Healthcheck function
        run: cd healthcheck && cp ../shared/*.py . && zip -r code.zip ./*.py
      - name: Update Healthcheck lambda function code
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:eu-west-2:730319765130:function:bcss-comms-healthcheck-dev \
            --zip-file fileb://healthcheck/code.zip \
            --region eu-west-2
      - name: Create zip file for Callback Simulator function
        run: cd callback_simulator && cp ../shared/*.py . && zip -r code.zip ./*.py
      - name: Update Callback Simulator lambda function code
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:eu-west-2:730319765130:function:bcss-comms-callback-simulator-dev \
            --zip-file fileb://callback_simulator/code.zip \
            --region eu-west-2
