name: Deploy Batch Notification Processor Lambda

on:
  push:
    branches: [*]

jobs:
  AssumeRoleAndUpdateAWS:
    name: "Assume AWS Role and Deploy Changes to Lambda"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # Get AWS Role to gain access
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::730319765130:role/bcss-github-actions-lambda-access
          aws-region: eu-west-2
      # Should have AWS Access at this point

      - name: Install zip tool
        uses: montudor/action-zip@v1

      - name: Create zip file for Lambda function
        run: cd batch_notification_processor && zip -r code.zip .

      - name: Check lambda exists
        id: check_lambda
        run: |
          if aws lambda get-function --function-name arn:aws:lambda:eu-west-2:730319765130:function:batch_notification_processor; then
            echo "Lambda function exists"
            echo "::set-output name=exists::true"
          else
            echo "Lambda function does not exist"
            echo "::set-output name=exists::false"
          fi