name: Deploy BCSS Callback Lambda

on:
  push:
    paths:
      - "bcss-notify-callback/**"
    branches: [main]
  workflow_dispatch:

jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
#      Get AWS Role to gain access
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::730319765130:role/bcss-github-actions-lambda-access
          aws-region: eu-west-2
#          Should have AWS Access at this point

      - name: Install zip tool
        uses: montudor/action-zip@v1
      - name: Create zip file for Lambda function
        run: cd bcss-notify-callback && zip -r code.zip .
      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest
        with:
          args:
            "lambda update-function-code \ 
            --function-name arn:aws:lambda:eu-west-2:730319765130:function:bcss-notify-callback
            --zip-file fileb://bcss-notify-callback/code.zip"