name: "Linting stage"

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, reopened]

jobs:
  linting:
    name: "linting"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Install Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Install dependencies"
        run: |
          pip install poetry
          poetry install --no-root

      - name: "Lint Python files:"
        run: |
          ./lint.sh

  pyright:
    name: "Pyright"
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: "Install Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Install dependencies"
        run: |
          pip install poetry
          poetry install --no-root

      - run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH

      - name: "Run Pyright"
        run: |
          ./pyright.sh