name: "Linting stage"

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, reopened]

jobs:
  linting:
    name: "linting"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Install Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Install dependencies"
        run: |
          pip install poetry
          poetry install --no-root

      - name: "Lint Python files:"
        run: |
          ./lint.sh

  pyright:
    - uses: actions/checkout@v3

    - run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        cache: 'poetry'

    - run: poetry install
    - run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH

    - uses: jakebailey/pyright-action@v2