name: Terraform Plan

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - none
    paths:
      - "terraform/**"

env:
  AWS_REGION: eu-west-2

jobs:
  plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    strategy:
      matrix:
        environment: [dev, prod]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive
        working-directory: ./terraform

      - name: Terraform Init
        run: |
          cd terraform/environments/${{ matrix.environment }}
          terraform init -backend-config="bucket=bcss-terraform-${{ matrix.environment == 'prod' && 'prod' || 'nonprod' }}-iac" \
                        -backend-config="key=bcss/infrastructure/communication-management/terraform.tfstate" \
                        -backend-config="region=${{ env.AWS_REGION }}" \
                        -backend-config="dynamodb_table=bcss-communication-management-terraform-lock-${{ matrix.environment }}"

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ./terraform/environments/${{ matrix.environment }}

      - name: Terraform Plan
        id: plan
        run: |
          cd terraform/environments/${{ matrix.environment }}
          terraform plan -no-color

      - name: Update Pull Request
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        env:
          PLAN: "${{ steps.plan.outputs.stdout }}"
          ENVIRONMENT: "${{ matrix.environment }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Validation for ${{ matrix.environment }} Environment ✅\`${{ steps.validate.outcome }}\`
            #### Terraform Plan for ${{ matrix.environment }} Environment 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan for ${{ matrix.environment }}</summary>

            \`\`\`terraform\n
            ${process.env.PLAN}
            \`\`\`

            </details>`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: output
            })
